### ISSUE TITLE
Upgrade to python 3

### ISSUE THREAD

**Issue by friedger** [friedger/matrix-blockstack-password-provider#3]
Currently, we use [zone-file-py](https://github.com/blockstack/zone-file-py) as a dependency. zone-file-py is only maintained for python 2 (https://github.com/blockstack/zone-file-py/issues/23)

This issue is about replacing zone-file-py.

**Comment by jaywink** [comment]
FYI did a [python3 port](https://pypi.org/project/blockstack-zones-py3/) in my spare time since it didn't look too difficult. No guarantees but tests do pass.

**Comment by friedger** [comment]
fixed in 0.7.0
